<?php
use Chibi\Sql as Sql;
use Chibi\Database as Database;

class Upgrade6 implements IUpgrade
{
	public static function execute()
	{
		Database::transaction(function()
		{
			$user = new UserEntity();
			$user->name = 'example';
			$user->email = null;
			$user->settings = new UserSettings();
			$user->settings->showGuestsLastUpdate = true;
			$user->passHash = null;
			UserService::saveOrUpdate($user);

			$lists =
			[
				'{"name":"Movies","visible":"1","content":{"columns":[{"id":1,"name":"Title","width":37.84,"align":"left"},{"id":2,"name":"My score","width":13.27,"align":"center"},{"id":"38","name":"Year","width":12.16,"align":"center"},{"id":3,"name":"Genres","width":28.99,"align":"left"}],"rows":[{"id":"6","content":["Fight Club","8","1999","drama"]},{"id":"7","content":["Pulp Fiction","9","1994","crime, drama, thriller"]},{"id":"8","content":["12 Angry Men","8","1957","drama"]},{"id":"9","content":["Green Mile[gray], The","10","1999","crime, drama"]},{"id":"10","content":["WALL-E","6","2008","animation, adventure"]},{"id":"11","content":["Die Hard","7","1988","action, thriller"]},{"id":"12","content":["Rush","4","2013","action, drama"]},{"id":"13","content":["V for Vendetta","7","2005","action, sci-fi, thriller"]},{"id":"14","content":["Thing[gray], The","-","1982","horror, sci-fi"]},{"id":"15","content":["Kill Bill vol 1","-","2003","action, crime"]},{"id":"16","content":["Kill Bill vol 2","-","2004","action, crime"]},{"id":"17","content":["Donnie Darko","-","2001","drama, sci-fi"]},{"id":"18","content":["Gravity","3","2013","drama, sci-fi, thriller"]},{"id":"19","content":["Groundhog Day","6","1993","comedy, drama"]},{"id":"20","content":["Truman Show[gray], The","9","1998","comedy, drama, sci-fi"]},{"id":"21","content":["Jurassic Park","4","1993","adventure, sci-fi"]},{"id":"22","content":["Twelve Monkeys","2","1995","sci-fi, thriller"]},{"id":"23","content":["Jaws","7","1975","horror, thriller"]},{"id":"24","content":["Beautiful Mind[gray], A","9","2001","drama"]},{"id":"25","content":["Toy Story","5","1995","animation, adventure, comedy"]},{"id":"26","content":["Up","7","2009","animation, adventure, drama"]},{"id":"27","content":["American Beauty","8","1999","drama"]},{"id":"28","content":["Memento","7","2000","thriller"]},{"id":"29","content":["Se7en","7","1995","crime, thriller"]},{"id":"30","content":["Forrest Gump","9","1994","drama, romance"]},{"id":"31","content":["Inception","8","2010","action, adventure"]},{"id":"32","content":["Shawshank Redemption[gray], The","10","1994","crime, drama"]},{"id":"33","content":["Godfather[gray], The","-","1972","crime, drama"]},{"id":"34","content":["Godfather 2[gray], The","-","1974","crime, drama"]},{"id":"35","content":["Matrix[gray], The","7","1999","action, sci-fi"]},{"id":"36","content":["Prestige[gray], The","10","2006","drama, thriller, sci-fi"]},{"id":"37","content":["Shining[gray], The","6","1980","horror"]}],"customCss":"","useCustomCss":false,"showRowIds":true,"sortStyle":"[[0,0]]","lastContentId":"38"}}',
				'{"name":"Video games","visible":"1","content":{"columns":[{"id":3,"name":"Status","width":17.81,"align":"center"},{"id":1,"name":"Title","width":37.87,"align":"left"},{"id":"8","name":"Comment","width":39.27,"align":"left"}],"rows":[{"id":4,"content":["[row:todo]backlogged","Beyond Good & Evil","apparently the best game ever"]},{"id":"5","content":["[row:todo]backlogged","Thief 2",""]},{"id":"6","content":["[row:done]completed","Thief",""]},{"id":"7","content":["[row:done]completed","Swapper, The","not worth it"]},{"id":"9","content":["[row:done]completed","Limbo","expected too much?"]},{"id":"10","content":["[row:playing]playing","Mass Effect 2",""]},{"id":"11","content":["[row:done]completed","Mass Effect 1",""]},{"id":"12","content":["[row:todo]backlogged","Mass Effect 3",""]},{"id":"13","content":["[row:done]completed","Worms Armageddon",""]},{"id":"14","content":["[row:done]completed","Thomas Was Alone","10/10 would jump again"]},{"id":"15","content":["[row:playing]struggling","Super Hexagon","GAME OVER. BEGIN. GAME OVER. BEGIN. GAME OVER. BEGIN."]},{"id":"16","content":["[row:done]completed","Deus Ex",""]},{"id":"17","content":["[row:todo]backlogged","Oddworld: Abe\'s Exoddus",""]},{"id":"18","content":["[row:done]completed","Oddworld: Abe\'s Oddysee","follow me"]},{"id":"19","content":["[row:done]completed","Prehistorik 2",""]},{"id":"20","content":["[row:todo]backlogged","MDK",""]},{"id":"21","content":["[row:todo]backlogged","MDK 2",""]},{"id":"22","content":["[row:playing]playing","Antichamber","what."]}],"customCss":"td:nth-child(2) { font-family: monospace; font-size: 13pt; }\n\nthead span { font-weight: bold; }\n\n.block-todo { background: #FFF5F5; }\n.block-done { background: #F5FFF5; }\n.block-playing { background: #E0EEFF; }","useCustomCss":true,"showRowIds":false,"sortStyle":"[[1,0]]","lastContentId":"22"}}',
				'{"name":"Todo list","visible":"1","content":{"columns":[{"id":1,"name":"Task","width":64.74,"align":"left"},{"id":2,"name":"Deadline","width":28.09,"align":"center"}],"rows":[{"id":4,"content":["[row:green][row:s]Feed cat","oops"]},{"id":"5","content":["[row:orange]Thesis","2014-10-30"]},{"id":"6","content":["[row:red]Get a hoverboard","2015"]},{"id":"7","content":["[row:orange]Upload photos somewhere","2014-04-28"]},{"id":"8","content":["[row:red]Gift for mom","2014-07-02"]},{"id":"13","content":["[row:orange]Buy useless junk again","2014-09"]},{"id":"14","content":["[row:green][row:s]Clean up HDDs","2014-05"]},{"id":"16","content":["[row:orange]Catch up with webcomics","2014-10"]}],"customCss":"@import url(\'http://fonts.googleapis.com/css?family=Gloria+Hallelujah\');\n\n#main { max-width: 700px; }\n\n#menu { margin: 18px 0 0 4px; }\n\n#search input {\nfont-family: \'Gloria Hallelujah\', cursive;\nfont-size: 12pt;\n}\n\n#search p { display: none; }\n\n#sidebar:after,\n#sidebar:before,\n#sidebar li.sep,\n#sidebar ul:after { display: none; }\n\n#sidebar li {\nbackground-image: none !important;\n}\n\n#sidebar a.list {\nbox-shadow: none;\nborder: none;\nfont-family: \'Gloria Hallelujah\', cursive;\ncolor: black !important;\nfont-size: 14pt;\n}\n\n#sidebar li a.list:hover { border: none !important; }\n\n#sidebar li a.list {\nborder-radius: 5px;\nbackground: #fdf791;\ncolor: white;\nmargin: 5px 0;\n}\n\n#sidebar li:hover a.list {\nbackground: #FCE557;\n}\n\n#sidebar li.active a.list {\nbackground: #FCE557;\nborder-radius: 5px;\nborder: none;\nmargin: 2px 0;\n}\n\n#list {\nposition: relative;\nfont-family: \'Gloria Hallelujah\', cursive;\nfont-size: 15pt;\nbackground: #fdf791;\nbox-shadow: 0px 5px 15px rgba(0, 0, 0, 0.1);\n}\n\n#list tbody tr td:first-child {\npadding-left: 1em;\n}\n\n#list tr:hover td { background: #FCE557 !important; }\n","useCustomCss":true,"showRowIds":false,"sortStyle":"[[1,1]]","lastContentId":"16"}}',
				'{"name":"HDDs","visible":"1","content":{"columns":[{"id":3,"name":"HDD 1","width":7.99,"align":"center"},{"id":4,"name":"HDD 2","width":8.6,"align":"center"},{"id":1,"name":"Name","width":57.12,"align":"left"},{"id":2,"name":"Size","width":17.44,"align":"center"}],"rows":[{"id":5,"content":["[no]","[yes]","Afro-Ken","110 [gray]MiB"]},{"id":"9","content":["[no]","[yes]","Top wo Nerae! 1 & 2","4.42 [gray]GiB"]},{"id":"10","content":["[yes]","[no]","Dennou Coil","8.18 [gray]GiB"]},{"id":"11","content":["[no]","[yes]","Katanagatari","9.00 [gray]GiB"]},{"id":"12","content":["[yes]","[no]","Cardcaptor Sakura","26.51 [gray]GiB"]},{"id":"13","content":["[yes]","[no]","Mushishi S1","8.09 [gray]GiB"]},{"id":"14","content":["[no]","[yes]","Mushishi OVA + S2","[gray]incomplete"]},{"id":"15","content":["[yes]","[yes]","Aria series + manga + stuff","27 [gray]GiB"]},{"id":"16","content":["[no]","[yes]","Haruhi","15.77 [gray]GiB"]},{"id":"17","content":["[yes]","[yes]","Hidamari Sketch + manga","21.16 [gray]GiB"]},{"id":"18","content":["[no]","[no]","Guilty Crown","[gray]just no"]},{"id":"19","content":["[yes]","[no]","Evangelion TV","10.50 [gray]GiB"]},{"id":"20","content":["[no]","[yes]","Evangelion Rebuild","28.43 [gray]GiB"]},{"id":"21","content":["[no]","[yes]","Inferno Cop","1.99 [gray]GiB"]},{"id":"22","content":["[yes]","[no]","K-On! 1 & 2 + specials + stuff","13.20 [gray]GiB"]},{"id":"23","content":["[yes]","[no]","Code Geass 1 & 2","[gray]incomplete"]},{"id":"24","content":["[yes]","[no]","Usagi drop + delicious manga","5.51 [gray]GiB"]}],"customCss":".span-yes:after {\ncontent: \'✔\';\ncolor: #3d993d;\n}\n\n.span-no:after {\ncontent: \'✘\';\ncolor: #ffdada;\n}\n\n.tablesorter-header span:after {\nbackground: none !important;\n}","useCustomCss":true,"showRowIds":true,"sortStyle":null,"lastContentId":"25"}}',
			];

			$importJobs = [];
			foreach ($lists as $list)
			{
				$importJobs []= Api::jobFactory('import-list', [
					'user-name' => 'example',
					'input-data' => $list]);
			}

			Api::forceSetApiUser($user);
			Api::run($importJobs);
		});
	}
}
