<?php
\Chibi\AssetViewDecorator::setTitle('lane&nbsp;&ndash; Login form');
?>

<h1>Login form</h1>

<form action="<?= \Chibi\UrlHelper::currentUrl() ?>" method="post">

	<?= HtmlHelper::labelDecorator('User name',
		HtmlHelper::textInputTag('name')) ?>

	<?= HtmlHelper::labelDecorator('Password',
		HtmlHelper::passwordInputTag('pass')) ?>

	<?= HtmlHelper::labelDecorator('',
		HtmlHelper::checkboxInputTag('remember', true),
		'remember me') ?>

	<?= HtmlHelper::labelDecorator(false,
		HtmlHelper::submitInputTag('Log in', ['class' => 'btn hl'])) ?>

</form>
