<?php
Assets::setTitle('lane&nbsp;&ndash; Registration form');
?>

<div id="auth-register">

	<h1>Registration form</h1>

	<form action="<?= \Chibi\Util\Url::currentUrl() ?>" method="post">

		<div class="form-wrapper">

			<?= HtmlHelper::labelDecorator('User name',
				HtmlHelper::textInputTag('name', ['placeholder' => 'e.g. darth_vader'])) ?>

			<?= HtmlHelper::labelDecorator('Password',
				HtmlHelper::passwordInputTag('pass1',
					['autocomplete' => 'off',
					'placeholder' => 'e.g. ' . str_repeat('•', 5)])) ?>

			<?= HtmlHelper::labelDecorator('Repeat password',
				HtmlHelper::passwordInputTag('pass2',
					['autocomplete' => 'off',
					'placeholder' => 'e.g. ' . str_repeat('•', 5)])) ?>

			<?= HtmlHelper::labelDecorator('E-mail (optional)',
				HtmlHelper::textInputTag('e-mail', ['placeholder' => 'e.g. vader@empire.gov'])) ?>

			<?= HtmlHelper::labelDecorator(false,
				HtmlHelper::submitInputTag('Register', ['class' => 'btn hl'])) ?>

		</div>

	</form>

</div>
