<?php
\Chibi\AssetViewDecorator::addStylesheet('popups.css');
\Chibi\AssetViewDecorator::addScript('popups.js');
\Chibi\AssetViewDecorator::addScript('index.js');
?>

<a href="<?= \Chibi\UrlHelper::absoluteUrl('/') ?>">
	<img src="<?= \Chibi\UrlHelper::absoluteUrl('/img/logo.png') ?>" alt=""/>
</a>
<br/>

<?php $this->renderFile('messages') ?>

<ul>
	<li>
		<a id="login" href="<?= \Chibi\UrlHelper::route('auth', 'login') ?>">Log in</a>
	</li>
	<li>
		<a id="register" href="<?= \Chibi\UrlHelper::route('auth', 'register') ?>">Register</a>
	</li>
</ul>
