<?php
Assets::addStylesheet('index-text.css');
Assets::setTitle('lane&nbsp;&ndash; about');
?>

<div id="about" class="text">

	<section>
		<h1>About</h1>

		<p>Lane stands for <em>list and nothing else</em>. It&rsquo;s meant to be a centralized way of organizing
		various kinds of things&nbsp;&ndash; watched movies, completed video games, books on plan&#8209;to&#8209;read
		shelf, or files put on external HDDs&nbsp;&ndash; without the need of having separate accounts on pages like
		IMDB, Backloggery, Goodreads, or keeping an Excel file.</p>

		<p>Since each list can have its own CSS rules, you can make it look however you like. You can also use some
		tags like <code>[b]bold[/b]</code> or <code>[red]colors[/red]</code> to easily edit the look of single cells or
		entire rows. Read more about editing on the <?= HtmlHelper::wrapTag('a', ['href' =>
		\Chibi\Router::linkTo(['IndexController', 'helpAction'])], 'help page') ?>.</p>

		<p><?= HtmlHelper::wrapTag('a', ['href' => \Chibi\Router::linkTo(['AuthController', 'registerAction'])],
		'Register') ?> your own account, or <?= HtmlHelper::wrapTag('a', ['href' =>
		\Chibi\Router::linkTo(['AuthController', 'loginAction'])], 'log in') ?> if you already have one.</p>

		<p>If you&rsquo;re still not convinced, take a look at an <?= HtmlHelper::wrapTag('a', ['href' =>
		\Chibi\Router::linkTo(['IndexController', 'exampleAction'])], 'example lane') ?> and see the features.</p>
	</section>

	<section>
		<h1>Contact and technical info</h1>

		<p>You can send us a message at&nbsp;<?= EmailObfuscator::embedJavascript(sprintf('%s@%s',
		getConfig()->mail->userContact, getConfig()->mail->domain)) ?></p>

		<p>Lane is <a href="https://github.com/rr-/lane/">open source</a> and released under MIT license.</p>

		<p>Developers might want to take a look at <?= HtmlHelper::wrapTag('a', ['href' =>
		\Chibi\Router::linkTo('IndexController', 'apiDocumentationAction'])], 'lane API documentation') ?>.</p>
	</section>

	<section>
		<h1>Privacy policy</h1>

		<p>Lane stores all your lists&rsquo; content along with their settings, custom CSS, and your account
		credentials&nbsp;&ndash; user name, hashed password, plus optional e&#8209;mail&nbsp;address used to reset your
		password. If you want, you can tell your browser to remember your credentials, which will set a cookie so you
		don&rsquo;t need to enter them all the time. Cookies are also used by Google Analytics, which gives us feedback
		about page views, and Google AdSense that displays ads. You can block accepting cookies in your browser
		settings.</p>

		<p>Lists can be set as private, which makes them visible to their owner only. Guests or other registered users
		cannot view your private lists.</p>

		<p>You can delete your account at any time. Doing so will remove <em>all</em> your data.</p>
	</section>

</div>
