<?php
\Chibi\AssetViewDecorator::setTitle('lane&nbsp;&ndash; list and nothing else');
\Chibi\AssetViewDecorator::addStylesheet('core.css');
\Chibi\AssetViewDecorator::addScript('http://code.jquery.com/jquery-1.11.0.min.js');
\Chibi\AssetViewDecorator::addScript('http://code.jquery.com/ui/1.10.4/jquery-ui.min.js');
\Chibi\AssetViewDecorator::addScript('common.js');
?>

<head>
	<meta charset="utf-8"/>

	<?= HtmlHelper::tag('meta', [
		'name' => 'robots',
		'content' => $this->context->allowIndexing
			? 'index, nofollow'
			: 'noindex, nofollow']) ?>

	<?= HtmlHelper::tag('meta', [
		'name' => 'application-name',
		'content' => 'lane - list and nothing else',
		'data-current-url' => \Chibi\UrlHelper::currentUrl(),
		'data-job-executor-url' => JobHelper::getJobExecutorUrl()], true) ?>

	<?= HtmlHelper::tag('link', [
		'rel' => 'icon',
		'type' => 'image/png',
		'href' => \Chibi\UrlHelper::absoluteUrl('/img/favicon.png')], true) ?>

	<?php if ($this->config->main->enableAnalytics): ?>
		<script type="text/javascript">
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
			ga('create', 'UA-37915710-2', 'lane.pl');
			ga('send', 'pageview');
		</script>
	<?php endif ?>

</head>
