<!DOCTYPE html>
<html>
<?php \Chibi\View::render('layout-head-common', $this->context) ?>
<body class="logo">
	<div id="main">
		<a class="logo" href="<?= \Chibi\Util\Url::makeAbsolute('/') ?>">
			<img src="<?= \Chibi\Util\Url::makeAbsolute('/img/logo.png') ?>" alt=""/>
		</a>
		<br/>

		<div class="content-wrapper">
			<?php \Chibi\View::render('messages', $this->context) ?>
			<?php \Chibi\View::render($this->context->viewName, $this->context) ?>
			<div class="clear"></div>

			<?php if (isset($this->context->returnLink)): ?>
				<div class="return-link-wrapper">
					<?= HtmlHelper::wrapTag('a',
						[
							'class' => 'btn hl return-link',
							'href' => $this->context->returnLink],
						$this->context->returnLinkText);
					?>
				</div>
			<?php endif ?>
		</div>

		<div class="clear"></div>
		<footer>
			<p>Load: <?= sprintf('%.07fs', getUptime()) ?></p>
		</footer>
	</div>
</body>
</html>
