<!DOCTYPE html>
<html>
<?= $this->renderFile('layout-head-common') ?>
<body>
	<div id="main" class="logo">
		<a href="<?= \Chibi\UrlHelper::absoluteUrl('/') ?>">
			<img src="<?= \Chibi\UrlHelper::absoluteUrl('/img/logo.png') ?>" alt=""/>
		</a>
		<br/>

		<div class="content-wrapper">
			<?php $this->renderFile('messages') ?>
			<?php $this->renderView() ?>
			<div class="clear"></div>

			<?php if (isset($this->context->returnLink)): ?>
				<?= HtmlHelper::tag('a', ['href' => $this->context->returnLink]); ?>
					<?= $this->context->returnLinkText ?>
				<?= HtmlHelper::tagClose('a'); ?>
			<?php endif ?>
		</div>

		<div class="clear"></div>
		<footer>
			<p>Load: <?= sprintf('%.07fs', Bootstrap::getUptime()) ?></p>
		</footer>
	</div>
</body>
</html>
