<!DOCTYPE html>
<html>
<?= $this->renderFile('layout-head-common') ?>
<body class="logo">
	<div id="main">
		<a class="logo" href="<?= \Chibi\UrlHelper::absoluteUrl('/') ?>">
			<img src="<?= \Chibi\UrlHelper::absoluteUrl('/img/logo.png') ?>" alt=""/>
		</a>
		<br/>

		<div class="content-wrapper">
			<?php $this->renderFile('messages') ?>
			<?php $this->renderView() ?>
			<div class="clear"></div>

			<?php if (isset($this->context->returnLink)): ?>
				<div class="return-link-wrapper">
					<?= HtmlHelper::wrapTag('a',
						[
							'class' => 'btn hl return-link',
							'href' => $this->context->returnLink],
						$this->context->returnLinkText);
					?>
				</div>
			<?php endif ?>
		</div>

		<div class="clear"></div>
		<footer>
			<p>Load: <?= sprintf('%.07fs', Bootstrap::getUptime()) ?></p>
		</footer>
	</div>
</body>
</html>
