<?php
\Chibi\AssetViewDecorator::addStylesheet('popups.css');
\Chibi\AssetViewDecorator::addStylesheet('list.css');
\Chibi\AssetViewDecorator::addScript('popups.js');
\Chibi\AssetViewDecorator::addScript('list.js');
\Chibi\AssetViewDecorator::addScript('queue.js');
?>

<?= $this->renderFile('list-sidebar') ?>

<div id="outer-content">
	<div id="inner-header">
		<?= $this->renderFile('list-header') ?>
	</div>

	<div id="inner-content">
		<?php $this->renderFile('messages') ?>
		<?php $this->renderFile('list-content') ?>
	</div>
</div>
