<div id="list-add">

	<h1>Add new list</h1>

	<form action="<?= \Chibi\UrlHelper::currentUrl() ?>" method="post">

		<?= HtmlHelper::labelDecorator('List name',
			HtmlHelper::textInputTag('name')) ?>

		<?= HtmlHelper::labelDecorator('Visibility',
			HtmlHelper::checkboxInputTag('visible', true),
			'visible to everyone') ?>

		<?= HtmlHelper::labelDecorator(false,
			HtmlHelper::submitInputTag('Create new list', ['class' => 'btn hl'])) ?>

	</form>

</div>
