<h1>Edit list <em><?= htmlspecialchars($this->context->list->name) ?></em></h1>

<?php
\Chibi\AssetViewDecorator::addStylesheet('list-settings.css');
\Chibi\AssetViewDecorator::addScript('list-settings.js');
\Chibi\AssetViewDecorator::addScript('queue.js');

$alignments = [
	ListColumn::ALIGN_LEFT => 'left',
	ListColumn::ALIGN_CENTER => 'center',
	ListColumn::ALIGN_RIGHT => 'right',
];
?>

<?= HtmlHelper::tag('form', [
	'action' => \Chibi\UrlHelper::currentUrl(),
	'method' => 'post',
	'id' => 'list-settings',
	'data-list-id' => $this->context->list->urlName,
	'data-list-columns' => json_encode($this->context->list->content->columns),
	'data-last-content-id' => $this->context->list->content->lastContentId,
	], false) ?>

	<div class="basic-settings">
		<?= HtmlHelper::labelDecorator('List name',
			HtmlHelper::textInputTag('name', ['placeholder' => 'Some name…', 'value' => $this->context->list->name])) ?>

		<?= HtmlHelper::labelDecorator('Visibility',
			HtmlHelper::checkboxInputTag('visibility', $this->context->list->visible),
			'visible to everyone') ?>

		<?= HtmlHelper::labelDecorator('Row IDs',
			HtmlHelper::checkboxInputTag('row-ids', $this->context->list->content->showRowIds),
			'show row numbers') ?>

		<?= HtmlHelper::labelDecorator('User CSS',
			HtmlHelper::checkboxInputTag('custom-css', $this->context->list->content->css != '', ['class' => 'custom-css']),
			'enable custom CSS') ?>
	</div>

	<ul class="ops">
		<li>
			<?= HtmlHelper::buttonInputTag('Delete this list', ['class' => 'btn hl delete']) ?>
		</li>
		<li>
			<?= HtmlHelper::buttonInputTag('Save current sort', ['class' => 'btn hl save-sort', 'style' => 'display: none']) ?>
		</li>
	</ul>

	<div class="clear"></div>

	<table class="column-manager">
		<thead>
			<tr>
				<th class="drag"></th>
				<th class="text">Column header</th>
				<th class="align">Text align</th>
				<th class="delete">Delete</th>
			</tr>
		</thead>

		<tbody>
		</tbody>

		<tfoot>
			<tr>
				<td></td>
				<td colspan="3">
					<?= HtmlHelper::buttonInputTag('Add new column', ['class' => 'btn add-column']) ?>
				</td>
			</tr>
		</tfoot>
	</table>

	<div class="custom-css-edit">
		<p>Custom CSS</p>
		<textarea name="custom-css"><?= TextHelper::keepWhitespace($this->context->list->content->css) ?></textarea>
	</div>

	<div class="submit">
		<?= HtmlHelper::submitInputTag('Save changes', ['class' => 'btn save-changes hl']) ?>
		<?= HtmlHelper::buttonInputTag('Cancel', ['class' => 'btn cancel']) ?>
	</div>

<?= HtmlHelper::tagClose('form') ?>
