<div id="sidebar">
	<a href="<?= \Chibi\UrlHelper::absoluteUrl('/') ?>">
		<img src="<?= \Chibi\UrlHelper::absoluteUrl('/img/logo-small.png') ?>" alt=""/>
	</a>

	<p id="save-info">
		<?php if (isset($this->context->list) and $this->context->list->lastUpdate !== null): ?>
			<?= 'updated ' . TextHelper::formatTimeDelta(time() - $this->context->list->lastUpdate) ?>
		<?php else: ?>
			&nbsp;
		<?php endif ?>
	</p>

	<?php if (!empty($this->context->lists)): ?>
		<div id="sidebar-nav">
			<ul id="lists">
			<?php foreach ($this->context->lists as $list): ?>
				<?= HtmlHelper::tag('li', (isset($this->context->list) and $list->urlName == $this->context->list->urlName) ? ['class' => 'active'] : []) ?>
					<a title="<?= $list->name ?>" href="<?= \Chibi\UrlHelper::route('list', 'view', ['userName' => $this->context->user->name, 'id' => $list->urlName]) ?>">
						<?= $list->name ?>
					</a>
				<?= HtmlHelper::tagClose('li') ?>
			<?php endforeach ?>
			</ul>

			<hr/>

			<?php if ($this->context->canEdit): ?>
				<ul id="list-management">
					<li>
						<a class="add-list" href="<?= \Chibi\UrlHelper::route('list', 'add', ['userName' => $this->context->user->name]) ?>">
							Add new list…
						</a>
					</li>
				</ul>
			<?php endif ?>
		</div>
	<?php endif ?>
</div>
