<?php if (!isset($this->context->list)) return ?>

<?php
\Chibi\AssetViewDecorator::setTitle($this->context->user->name . '&rsquo;s lane&nbsp;&ndash; ' . $this->context->list->name);
\Chibi\AssetViewDecorator::addStylesheet('list-content.css');
\Chibi\AssetViewDecorator::addScript('list-content.js');
if ($this->context->list->content->css != '')
	\Chibi\AssetViewDecorator::addStylesheet(\Chibi\UrlHelper::route('list', 'custom-css', ['userName' => $this->context->user->name, 'id' => $this->context->list->urlName]));

$alignments = [];
$alignments[ListColumn::ALIGN_LEFT] = 'col-left';
$alignments[ListColumn::ALIGN_CENTER] = 'col-center';
$alignments[ListColumn::ALIGN_RIGHT] = 'col-right';
?>

<?= HtmlHelper::tag('table', [
	'id' => 'list',
	'data-can-edit' => $this->context->canEdit ? '1' : '0',
	'data-show-row-ids' => $this->context->list->content->showRowIds,
	'data-list-id' => $this->context->list->urlName,
	'data-list-rows' => json_encode($this->context->list->content->rows),
	'data-list-columns' => json_encode($this->context->list->content->columns),
	'data-last-content-id' => $this->context->list->content->lastContentId], false) ?>

	<thead>
		<tr>
			<?php foreach (ListService::getColumns($this->context->list) as $columnIndex => $column): ?>
				<?= HtmlHelper::tag('th', [
					'class' => $alignments[$column->align],
					'style' => sprintf('width: %.02f%%', $column->width),
				], false) ?>
					<?= htmlspecialchars($column->name) ?>
				<?= HtmlHelper::tagClose('th') ?>
			<?php endforeach ?>
			<?php if ($this->context->canEdit): ?>
				<th class="row-ops"></th>
			<?php endif ?>
		</tr>
	</thead>

	<tbody>
	</tbody>

<?= HtmlHelper::tagClose('table') ?>

<?php if ($this->context->canEdit): ?>
	<div id="add-row">
		<input type="button" value="Add new row"/>
	</div>
<?php endif ?>
