<h1>Add new list</h1>

<form action="<?= \Chibi\UrlHelper::route('list', 'add') ?>" method="post">

	<?= HtmlHelper::labelDecorator('List name',
		HtmlHelper::textInputTag('name')) ?>

	<?= HtmlHelper::labelDecorator('Visibility',
		HtmlHelper::checkboxInputTag('visible', true),
		'visible to everyone') ?>

	<?= HtmlHelper::labelDecorator(false,
		HtmlHelper::submitInputTag('Create new list')) ?>

</form>
