<?php
Assets::addScript('list-import.js');
?>

<div id="list-import">

	<h1>Import new list</h1>

	<form action="<?= \Chibi\Util\Url::currentUrl() ?>" method="post" enctype="multipart/form-data">

		<?= HtmlHelper::labelDecorator('JSON file',
			HtmlHelper::fileInputTag('file', [])) ?>

		<?= HtmlHelper::labelDecorator(false,
			HtmlHelper::submitInputTag('Create new list', ['class' => 'btn hl'])) ?>

	</form>

</div>
