<?php if (!isset($this->context->list)) return ?>

<?php
if ($this->context->list->content->css != '')
	\Chibi\AssetViewDecorator::addStylesheet(\Chibi\UrlHelper::route('list', 'custom-css', ['userName' => $this->context->user->name, 'id' => $this->context->list->urlName]));

$alignments = [];
$alignments[ListColumn::ALIGN_LEFT] = 'col-left';
$alignments[ListColumn::ALIGN_CENTER] = 'col-center';
$alignments[ListColumn::ALIGN_RIGHT] = 'col-right';

$showCell = function($text)
{
?>
	<td>
		<span class="content"><?= $text ?></span>
		<?php if ($this->context->canEdit): ?>
			<input type="text"/>
			<a href="#" class="edit-content">
				<i class="icon-edit"></i>
			</a>
		<?php endif ?>
	</td>
<?php
}
?>

<?= HtmlHelper::tag('table', [
	'id' => 'list',
	'data-list-id' => $this->context->list->urlName,
	'data-last-content-id' => $this->context->list->content->lastContentId], false) ?>

	<thead>
		<tr>
			<?php foreach (ListService::getColumns($this->context->list) as $columnIndex => $column): ?>
				<?= HtmlHelper::tag('th', [
					'class' => $alignments[$column->align],
					'style' => sprintf('width: %.02f%%', $column->width),
				], false) ?>
					<?= htmlspecialchars($column->name) ?>
				<?= HtmlHelper::tagClose('th') ?>
			<?php endforeach ?>
		</tr>
	</thead>

	<tbody>
		<?php foreach (ListService::getRows($this->context->list) as $rowIndex => $row): ?>
			<tr>
				<?php foreach (ListService::getColumns($this->context->list) as $columnIndex => $column): ?>
					<?= $showCell($row->content[$columnIndex]) ?>
				<?php endforeach ?>
			</tr>
		<?php endforeach ?>
	</tbody>

	<tfoot>
		<tr class="row-template">
			<?php foreach (ListService::getColumns($this->context->list) as $columnIndex => $column): ?>
				<? $showCell('') ?>
			<?php endforeach ?>
		</tr>
	</tfoot>

<?= HtmlHelper::tagClose('table') ?>

<?php if ($this->context->canEdit): ?>
	<div id="add-row">
		<input type="button" value="Add new row"/>
	</div>
<?php endif ?>
