<?php
\Chibi\AssetViewDecorator::addStylesheet('list-sidebar.css');
\Chibi\AssetViewDecorator::addScript('list-sidebar.js');
?>

<div id="sidebar" data-can-edit="<?= intval($this->context->canEdit) ?>">
	<a href="<?= \Chibi\UrlHelper::absoluteUrl('/') ?>">
		<img src="<?= \Chibi\UrlHelper::absoluteUrl('/img/logo-small.png') ?>" alt=""/>
	</a>

	<p id="save-info">
		<?php if (isset($this->context->list) and $this->context->list->lastUpdate !== null): ?>
			<?= 'updated ' . TextHelper::formatTimeDelta(time() - $this->context->list->lastUpdate) ?>
		<?php else: ?>
			&nbsp;
		<?php endif ?>
	</p>

	<?php if (!empty($this->context->lists)): ?>
		<div id="sidebar-nav">
			<ul id="lists">
				<?php foreach ($this->context->lists as $list): ?>
					<?php
						$active = (isset($this->context->list) and
							$list->urlName == $this->context->list->urlName);

						echo HtmlHelper::tag('li', [
							'data-list-id' => $list->urlName,
							'class' => $active ? 'active' : '']);

						echo HtmlHelper::tag('a', [
							'class' => 'list',
							'href' => \Chibi\UrlHelper::route('list', 'view', ['userName' => $this->context->user->name, 'id' => $list->urlName]),
							'title' => $list->name]);

						echo htmlspecialchars($list->name);

						echo HtmlHelper::tagClose('a');
						echo HtmlHelper::tagClose('li');
					?>
				<?php endforeach ?>
			</ul>

			<hr/>

			<?php if ($this->context->canEdit): ?>
				<ul id="list-management">
					<li>
						<a class="add-list" href="<?= \Chibi\UrlHelper::route('list', 'add', ['userName' => $this->context->user->name]) ?>">
							Add new list…
						</a>
					</li>

					<li>
						<a class="settings" href="<?= \Chibi\UrlHelper::route('list', 'settings', ['userName' => $this->context->user->name, 'id' => $this->context->list->urlName]) ?>">
							List settings…
						</a>
					</li>
				</ul>
			<?php endif ?>
		</div>
	<?php endif ?>
</div>
