<div id="top-menu">
	<div id="search">
		<?php if (isset($this->context->list)): ?>
			<?= HtmlHelper::textInputTag('search', ['placeholder' => 'Search on this list…']) ?>
		<?php endif ?>
		<p><?= $this->context->user->name ?>&rsquo;s lane</p>
	</div>

	<?php
	Assets::addStylesheet('list-top-menu.css');
	Assets::addScript('list-top-menu.js');
	?>

	<ul class="big-buttons">
		<?php if (Auth::isLoggedIn()
			and isset($this->context->list)
			and $this->context->list->userId != Auth::getLoggedInUser()->id): ?>

			<li>
				<?= HtmlHelper::wrapTag('a', [
					'class' => 'back-to-lane',
					'href' => \Chibi\Router::linkTo(['ListController', 'viewAction'], [
						'userName' => Auth::getLoggedInUser()->name])],
					'<i class="icon icon-lane"></i> <span>Back to your lane</span>') ?>
			</li>
		<?php endif ?>

		<?php if ($this->context->canEdit): ?>
			<li>
				<?= HtmlHelper::wrapTag('a', [
					'class' => 'add-list',
					'href' => \Chibi\Router::linkTo(['ListController', 'addAction'], [
						'userName' => $this->context->user->name])],
					'<i class="icon icon-add"></i> <span>Add new list</span>') ?>
			</li>

			<?php if (isset($this->context->list)): ?>
				<li>
					<?= HtmlHelper::wrapTag('a', [
						'class' => 'list-settings',
						'href' => \Chibi\Router::linkTo(['ListController', 'settingsAction'], [
							'userName' => $this->context->user->name,
							'id' => $this->context->list->urlName])],
						'<i class="icon icon-settings"></i> <span>List settings</span>') ?>
				</li>
			<?php endif ?>
		<?php endif ?>

		<li id="menu-trigger">
			<a href="#"><i class="icon icon-menu"></i> <span>Menu</span></a>
		</li>
	</ul>

	<div id="menu">
		<ul>
			<?php
				$links = [];
				if (Auth::isLoggedIn())
				{
					$links []= [
						'icon-user',
						'account-settings',
						'Account settings',
						\Chibi\Router::linkTo(['UserController', 'accountSettingsAction'], [
							'userName' => Auth::getLoggedInUser()->name])];

					if (isset($this->context->list) and $this->context->list->userId == Auth::getLoggedInUser()->id)
					{
						$links []= [
							'icon-eye',
							'view-as-guest',
							'View as guest',
							\Chibi\Router::linkTo(['ListController', 'viewAction'], [
								'userName' => $this->context->user->name,
								'id' => $this->context->list->urlName, 'guest' => 'guest'])];
					}

					$links []= null;

					if (isset($this->context->list) and $this->context->list->userId == Auth::getLoggedInUser()->id)
					{
						$links []= [
							'icon-import',
							'import',
							'Import new list',
							\Chibi\Router::linkTo(['ListController', 'importAction'], [
								'userName' => $this->context->user->name])];
					}

					if (isset($this->context->list))
					{
						$links []= [
							'icon-export',
							'export',
							$this->context->list->userId != Auth::getLoggedInUser()->id
								? 'Steal this list'
								: 'Export this list',
							\Chibi\Router::linkTo(['ListController', 'exportAction'], [
								'userName' => $this->context->user->name,
								'id' => $this->context->list->urlName])];
					}

				}
				elseif (Auth::isTemporarilyLoggedOut())
				{
					$links []= [
						'icon-edit',
						'view-as-guest',
						'Back to edit mode',
						\Chibi\Router::linkTo(['ListController', 'viewAction'], [
							'userName' => $this->context->user->name,
							'id' => $this->context->list->urlName])];
				}

				$links []= null;

				$links []= [
					'icon-question',
					'help',
					'Editing help',
					\Chibi\Router::linkTo(['IndexController', 'helpAction'])];

				$links []= [
					'icon-information',
					'about',
					'About',
					\Chibi\Router::linkTo(['IndexController', 'aboutAction'])];

				$links []= null;

				if (Auth::isLoggedIn())
				{
					$links []= [
						'icon-exit',
						'logout',
						'Log out',
						\Chibi\Router::linkTo(['AuthController', 'logoutAction'])];
				}
				else
				{
					$links []= [
						'icon-key',
						'login',
						'Log in',
						\Chibi\Router::linkTo(['AuthController', 'loginAction'])];

					$links []= [
						'icon-user-add',
						'register',
						'Register',
						\Chibi\Router::linkTo(['AuthController', 'registerAction'])];
				}
			?>
			<?php foreach ($links as $link): ?>
				<?php if ($link === null): ?>
				<hr/>
				<?php else: ?>
					<?php list ($iconClass, $itemClass, $text, $url) = $link ?>
					<li>
						<?= HtmlHelper::wrapTag('a',
							['href' => $url, 'class' => $itemClass],
							'<i class="icon ' . $iconClass . '"></i>' . $text) ?>
					</li>
				<?php endif ?>
			<?php endforeach ?>
		</ul>
	</div>
</div>
