<div id="top-menu">
	<div id="search">
		<?php if (isset($this->context->list)): ?>
			<?= HtmlHelper::textInputTag('search', ['placeholder' => 'Search on this list…']) ?>
		<?php endif ?>
		<p><?= $this->context->user->name ?>&rsquo;s lane</p>
	</div>

	<?php
	\Chibi\AssetViewDecorator::addStylesheet('list-top-menu.css');
	\Chibi\AssetViewDecorator::addScript('list-top-menu.js');
	?>

	<ul class="big-buttons">
		<?php if ($this->context->canEdit): ?>
			<li>
				<?= HtmlHelper::wrapTag('a', [
					'class' => 'add-list',
					'href' => \Chibi\UrlHelper::route('list', 'add', [
						'userName' => $this->context->user->name])],
					'<i class="icon icon-add"></i> <span>Add new list</span>') ?>
			</li>

			<?php if (isset($this->context->list)): ?>
				<li>
					<?= HtmlHelper::wrapTag('a', [
						'class' => 'list-settings',
						'href' => \Chibi\UrlHelper::route('list', 'settings', [
							'userName' => $this->context->user->name,
							'id' => $this->context->list->urlName])],
						'<i class="icon icon-settings"></i> <span>List settings</span>') ?>
				</li>
			<?php endif ?>
		<?php endif ?>

		<li id="menu-trigger">
			<a href="#"><i class="icon icon-menu"></i> <span>Menu</span></a>
		</li>
	</ul>

	<div id="menu">
		<ul>
			<?php
				$links = [];
				if (Auth::isLoggedIn())
				{
					$links []= [
						'icon-user',
						'account-settings',
						'Account settings',
						\Chibi\UrlHelper::route('user', 'account-settings', [
							'userName' => Auth::getLoggedInUser()->name])];

					$links []= [
						'icon-import',
						'import',
						'Import new list',
						\Chibi\UrlHelper::route('list', 'import', [
							'userName' => $this->context->user->name])];

					if (isset($this->context->list))
					{
						$links []= [
							'icon-export',
							'export',
							'Export this list',
							\Chibi\UrlHelper::route('list', 'export', [
								'userName' => $this->context->user->name,
								'id' => $this->context->list->urlName])];
					}

					if (isset($this->context->list) and $this->context->list->userId == Auth::getLoggedInUser()->id)
					{
						$links []= [
							'icon-eye',
							'view-as-guest',
							'View as guest',
							\Chibi\UrlHelper::route('list', 'view', [
								'userName' => $this->context->user->name,
								'id' => $this->context->list->urlName, 'guest' => 'guest'])];
					}

				}
				elseif (Auth::isTemporarilyLoggedOut())
				{
					$links []= [
						'icon-edit',
						'view-as-guest',
						'Back to edit mode',
						\Chibi\UrlHelper::route('list', 'view', [
							'userName' => $this->context->user->name,
							'id' => $this->context->list->urlName])];
				}

				$links []= [
					'icon-question',
					'help',
					'Editing help',
					\Chibi\UrlHelper::route('index', 'help')];

				$links []= [
					'icon-information',
					'about',
					'About',
					\Chibi\UrlHelper::route('index', 'about')];

				if (Auth::isLoggedIn())
				{
					$links []= [
						'icon-exit',
						'logout',
						'Log out',
						\Chibi\UrlHelper::route('auth', 'logout')];
				}
				else
				{
					$links []= [
						'icon-key',
						'login',
						'Log in',
						\Chibi\UrlHelper::route('auth', 'login')];

					$links []= [
						'icon-user-add',
						'register',
						'Register',
						\Chibi\UrlHelper::route('auth', 'register')];
				}
			?>
			<?php foreach ($links as $link): ?>
				<?php list ($iconClass, $itemClass, $text, $url) = $link ?>
				<li>
					<?= HtmlHelper::wrapTag('a',
						['href' => $url, 'class' => $itemClass],
						'<i class="icon ' . $iconClass . '"></i>' . $text) ?>
				</li>
			<?php endforeach ?>
		</ul>
	</div>
</div>
