<?php if (!isset($this->context->list)) return ?>

<?php
$alignments = [];
$alignments[ListColumn::ALIGN_LEFT] = 'col-left';
$alignments[ListColumn::ALIGN_CENTER] = 'col-center';
$alignments[ListColumn::ALIGN_RIGHT] = 'col-right';

$showCell = function($text)
{
?>
	<td>
		<span class="content"><?= $text ?></span>
		<?php if ($this->context->canEdit): ?>
			<input type="text"/>
			<a href="#" class="edit-content">
				<i class="icon-edit"></i>
			</a>
		<?php endif ?>
	</td>
<?php
}
?>

<table id="list" data-list-id="<?= $this->context->list->urlName ?>">
	<thead>
		<tr>
			<?php foreach (ListService::getColumns($this->context->list) as $columnIndex => $column): ?>
				<?= HtmlHelper::tag('th', [
					'class' => $alignments[$column->align],
					'style' => sprintf('width: %.02f%%', $column->width),
				], false) ?>
					<?= $column->name ?>
				<?= HtmlHelper::tagClose('th') ?>
			<?php endforeach ?>
		</tr>
	</thead>

	<tbody>
		<?php foreach (ListService::getRows($this->context->list) as $rowIndex => $row): ?>
			<tr>
				<?php foreach (ListService::getColumns($this->context->list) as $columnIndex => $column): ?>
					<?= $showCell($row->content[$columnIndex]) ?>
				<?php endforeach ?>
			</tr>
		<?php endforeach ?>
	</tbody>

	<tfoot>
		<tr class="row-template">
			<?php foreach (ListService::getColumns($this->context->list) as $columnIndex => $column): ?>
				<? $showCell('') ?>
			<?php endforeach ?>
		</tr>
	</tfoot>
</table>

<?php if ($this->context->canEdit): ?>
	<div id="add-row">
		<input type="button" value="Add new row"/>
	</div>
<?php endif ?>
