<?php
\Chibi\AssetViewDecorator::addStylesheet('menu.css');
\Chibi\AssetViewDecorator::addScript('menu.js');
?>

<div id="menu">
	<div id="menu-trigger">
		<a href="#"><i class="icon icon-menu"></i> Menu</a>
	</div>
	<ul>
		<?php
			$links = [];
			if ($this->context->isLoggedIn)
			{
				$links []= ['account-settings', \Chibi\UrlHelper::route('user', 'account-settings', ['userName' => $this->context->userLogged->name]), 'Account settings'];
				$links []= ['import', '#', 'Import new list'];
				$links []= ['export', '#', 'Export this list'];
			}

			$links []= ['help', \Chibi\UrlHelper::route('index', 'help'), 'Editing help'];
			$links []= ['about', \Chibi\UrlHelper::route('index', 'about'), 'About'];

			if ($this->context->isLoggedIn)
			{
				$links []= ['logout', \Chibi\UrlHelper::route('auth', 'logout'), 'Log out'];
			}
			else
			{
				$links []= ['login', \Chibi\UrlHelper::route('auth', 'login'), 'Log in'];
				$links []= ['register', \Chibi\UrlHelper::route('auth', 'register'), 'Register'];
			}
		?>
		<?php foreach ($links as $link): ?>
			<?php list ($class, $url, $text) = $link ?>
			<li>
				<a href="<?= $url ?>" class="<?= $class ?>">
					<?= $text ?>
				</a>
			</li>
		<?php endforeach ?>
	</ul>
</div>
