<?php
\Chibi\AssetViewDecorator::addStylesheet('user-account-settings.css');
\Chibi\AssetViewDecorator::addScript('user-account-settings.js');
?>

<div id="account-settings">

	<h1>Account settings</h1>

	<?= HtmlHelper::tag('form', [
		'action' => \Chibi\UrlHelper::currentUrl(),
		'method' => 'post',
		], false) ?>

		<div class="form-wrapper">
			<?= HtmlHelper::labelDecorator('Last update text',
				HtmlHelper::checkboxInputTag('show-guests-last-update', $this->context->user->settings->showGuestsLastUpdate),
				'show &ldquo;last save time&rdquo; to guests') ?>
		</div>

		<p>Enter your current password to change options below.</p>

		<div class="form-wrapper">
			<?= HtmlHelper::labelDecorator('Current password',
				HtmlHelper::passwordInputTag('current-password', ['autocomplete' => 'off'])) ?>

			<?= HtmlHelper::labelDecorator('New password',
				HtmlHelper::passwordInputTag('new-password1', ['autocomplete' => 'off'])) ?>

			<?= HtmlHelper::labelDecorator('Repeat new password',
				HtmlHelper::passwordInputTag('new-password2', ['autocomplete' => 'off'])) ?>

			<?= HtmlHelper::labelDecorator('E-mail address',
				HtmlHelper::textInputTag('new-e-mail', ['value' => $this->context->user->email])) ?>
		</div>

		<div class="submit">
			<div class="left">
			<?= HtmlHelper::submitInputTag('Save changes', ['class' => 'btn save-changes hl']) ?>
			<?= HtmlHelper::buttonInputTag('Cancel', ['style' => 'display: none', 'class' => 'btn cancel']) ?>
			</div>

			<div class="right">
				<?= HtmlHelper::buttonInputTag('More...', ['class' => 'btn more']) ?>
			</div>

			<div class="clear"></div>
		</div>

	<?= HtmlHelper::tagClose('form') ?>

	<div class="danger">
		<hr/>

		<p>If you want to permanently delete your account, consider exporting your lists data before taking the last step.</p>

		<?= HtmlHelper::tag('form', [
			'action' => \Chibi\UrlHelper::route('user', 'delete-account', ['userName' => $this->context->user->name]),
			'class' => 'inline delete-account',
			'method' => 'post',
			], false) ?>

			<div class="form-wrapper">
				<?= HtmlHelper::labelDecorator('Current password',
					HtmlHelper::passwordInputTag('current-password', ['autocomplete' => 'off'])) ?>
			</div>

			<div class="submit">

				<?= HtmlHelper::wrapTag('a', [
					'href' => \Chibi\URlHelper::route('list', 'export', ['userName' => $this->context->user->name]),
					'class' => 'btn export-all-data'], 'Export all data') ?>

				<?= HtmlHelper::submitInputTag('Delete account') ?>

			</div>

		<?= HtmlHelper::tagClose('form') ?>

	</div>
</div>
